In [11]:
import pandas as pd

In [12]:
car = pd.read_csv(r"C:\Users\Biplob\Desktop\Python for Machine Learning and Data Science\All Projects - Data Analytics\2. Data Analysis with Python  Cars Dataset\2. Cars Data1.csv")

In [13]:
car.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197

In [14]:
car.shape

(428, 15)

# 1) Instruction ( For Data Cleaning)
	#Find all null value in the dataset. If there is any null value in any column. then fill it with the mean of the column

In [17]:
car.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      2
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [18]:
car['Cylinders'].fillna(car['Cylinders'].mean(), inplace = True)

In [21]:
car.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

# 2)Question ( Based on Value Counts )
	Check what are the different types of Make are there in our dataset. And, what is the count(occurrence) of each make in     the data ?

In [22]:
car.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172

In [23]:
car['Make'].value_counts()

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Chrysler         15
Volkswagen       15
Mitsubishi       13
Dodge            13
Volvo            12
Jaguar           12
Hyundai          12
Subaru           11
Lexus            11
Mazda            11
Kia              11
Pontiac          11
Buick             9
Lincoln           9
Mercury           9
Cadillac          8
Saturn            8
GMC               8
Suzuki            8
Infiniti          8
Porsche           7
Saab              7
Acura             7
Land Rover        3
Oldsmobile        3
Jeep              3
Isuzu             2
MINI              2
Scion             2
Hummer            1
Name: Make, dtype: int64

# 3) Instruction (Filtering)
	Show all the records where Origin is Asia or Europe

In [24]:
car.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197

In [28]:
car[car['Origin'].isin(['Asia','Europe'])]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220,18,25,4013,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450,15,22,4024,109,191
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180,20,28,3131,95,159
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220,18,25,4035,109,192
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225,16,23,4023,110,180
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325,16,22,4824,111,184
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184,20,29,3219,107,176
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184,20,29,3197,107,177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190,16,18,3925,128,218
399,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,"$25,935","$23,520",3.4,6.0,190,14,17,4435,128,218
400,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130,29,36,2679,102,171
401,Volkswagen,Touareg V6,SUV,Europe,All,"$35,515","$32,243",3.2,6.0,220,15,20,5086,112,187
402,Volkswagen,Golf GLS 4dr,Sedan,Europe,Front,"$18,715","$17,478",2.0,4.0,115,24,31,2897,99,165
403,Volkswagen,GTI 1.8T 2dr hatch,Sedan,Europe,Front,"$19,825","$18,109",1.8,4.0,180,24,31,2934,99,168
404,Volkswagen,Jetta GLS TDI 4dr,Sedan,Europe,Front,"$21,055","$19,638",1.9,4.0,100,38,46,3003,99,172
405,Volkswagen,New Beetle GLS 1.8T 2dr,Sedan,Europe,Front,"$21,055","$19,638",1.8,4.0,150,24,31,2820,99,161
406,Volkswagen,Jetta GLI VR6 4dr,Sedan,Europe,Front,"$23,785","$21,686",2.8,6.0,200,21,30,3179,99,172
407,Volkswagen,New Beetle GLS convertible 2dr,Sedan,Europe,Front,"$23,215","$21,689",2.0,4.0,115,24,30,3082,99,161
408,Volkswagen,Passat GLS 4dr,Sedan,Europe,Front,"$23,955","$21,898",1.8,4.0,170,22,31,3241,106,185
409,Volkswagen,Passat GLX V6 4MOTION 4dr,Sedan,Europe,Front,"$33,180","$30,583",2.8,6.0,190,19,26,3721,106,185
410,Volkswagen,Passat W8 4MOTION 4dr,Sedan,Europe,Front,"$39,235","$36,052",4.0,8.0,270,18,25,3953,106,185
411,Volkswagen,Phaeton 4dr,Sedan,Europe,Front,"$65,000","$59,912",4.2,8.0,335,16,22,5194,118,204
412,Volkswagen,Phaeton W12 4dr,Sedan,Europe,Front,"$75,000","$69,130",6.0,12.0,420,12,19,5399,118,204
413,Volkswagen,Jetta GL,Wagon,Europe,Front,"$19,005","$17,427",2.0,4.0,115,24,30,3034,99,174
414,Volkswagen,Passat GLS 1.8T,Wagon,Europe,Front,"$24,955","$22,801",1.8,4.0,170,22,31,3338,106,184
415,Volkswagen,Passat W8,Wagon,Europe,Front,"$40,235","$36,956",4.0,8.0,270,18,25,4067,106,184
416,Volvo,XC90 T6,SUV,Europe,All,"$41,250","$38,851",2.9,6.0,268,15,20,4638,113,189
417,Volvo,S40 4dr,Sedan,Europe,Front,"$25,135","$23,701",1.9,4.0,170,22,29,2767,101,178
418,Volvo,S60 2.5 4dr,Sedan,Europe,All,"$31,745","$29,916",2.5,5.0,208,20,27,3903,107,180
419,Volvo,S60 T5 4dr,Sedan,Europe,Front,"$34,845","$32,902",2.3,5.0,247,20,28,3766,107,180
420,Volvo,S60 R 4dr,Sedan,Europe,All,"$37,560","$35,382",2.5,5.0,300,18,25,3571,107,181
421,Volvo,S80 2.9 4dr,Sedan,Europe,Front,"$37,730","$35,542",2.9,6.0,208,20,28,3576,110,190
422,Volvo,S80 2.5T 4dr,Sedan,Europe,All,"$37,885","$35,688",2.5,5.0,194,20,27,3691,110,190
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [26]:
car[(car['Origin'] == 'Asia') | (car['Origin'] == 'Europe')].head(50)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220,18,25,4013,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450,15,22,4024,109,191
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180,20,28,3131,95,159
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220,18,25,4035,109,192
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225,16,23,4023,110,180
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325,16,22,4824,111,184
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184,20,29,3219,107,176
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184,20,29,3197,107,177
30,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184,19,27,3560,107,177
31,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184,19,27,3461,107,176
32,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225,20,30,3285,107,176
33,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225,20,30,3285,107,176
34,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225,20,29,3483,107,176
35,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.0,184,19,28,3428,114,191
36,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225,19,28,3616,107,177
37,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.0,225,20,30,3472,114,191
38,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.0,325,18,26,3814,114,191
39,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8.0,325,18,26,4376,118,198
40,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.0,325,18,26,4464,123,204
41,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6.0,333,16,24,3415,108,177
42,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.0,333,16,23,3781,108,177
43,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895","$31,065",2.5,6.0,184,20,28,2932,98,161
44,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.0,6.0,225,21,29,2998,98,161
45,BMW,325xi Sport,Wagon,Europe,All,"$32,845","$30,110",2.5,6.0,184,19,26,3594,107,176
149,Honda,Civic Hybrid 4dr manual (gas/electric),Hybrid,Asia,Front,"$20,140","$18,451",1.4,4.0,93,46,51,2732,103,175
150,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110","$17,911",2.0,3.0,73,60,66,1850,95,155
151,Honda,Pilot LX,SUV,Asia,All,"$27,560","$24,843",3.5,6.0,240,17,22,4387,106,188
152,Honda,CR-V LX,SUV,Asia,All,"$19,860","$18,419",2.4,4.0,160,21,25,3258,103,179

In [27]:
car[(car['Origin'] == 'Asia') | (car['Origin'] == 'Europe')].tail(50)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
378,Toyota,RAV4,SUV,Asia,All,"$20,290","$18,553",2.4,4.0,161,22,27,3119,98,167
379,Toyota,Corolla CE 4dr,Sedan,Asia,Front,"$14,085","$13,065",1.8,4.0,130,32,40,2502,102,178
380,Toyota,Corolla S 4dr,Sedan,Asia,Front,"$15,030","$13,650",1.8,4.0,130,32,40,2524,102,178
381,Toyota,Corolla LE 4dr,Sedan,Asia,Front,"$15,295","$13,889",1.8,4.0,130,32,40,2524,102,178
382,Toyota,Echo 2dr manual,Sedan,Asia,Front,"$10,760","$10,144",1.5,4.0,108,35,43,2035,93,163
383,Toyota,Echo 2dr auto,Sedan,Asia,Front,"$11,560","$10,896",1.5,4.0,108,33,39,2085,93,163
384,Toyota,Echo 4dr,Sedan,Asia,Front,"$11,290","$10,642",1.5,4.0,108,35,43,2055,93,163
385,Toyota,Camry LE 4dr,Sedan,Asia,Front,"$19,560","$17,558",2.4,4.0,157,24,33,3086,107,189
386,Toyota,Camry LE V6 4dr,Sedan,Asia,Front,"$22,775","$20,325",3.0,6.0,210,21,29,3296,107,189
387,Toyota,Camry Solara SE 2dr,Sedan,Asia,Front,"$19,635","$17,722",2.4,4.0,157,24,33,3175,107,193
388,Toyota,Camry Solara SE V6 2dr,Sedan,Asia,Front,"$21,965","$19,819",3.3,6.0,225,20,29,3417,107,193
389,Toyota,Avalon XL 4dr,Sedan,Asia,Front,"$26,560","$23,693",3.0,6.0,210,21,29,3417,107,192
390,Toyota,Camry XLE V6 4dr,Sedan,Asia,Front,"$25,920","$23,125",3.0,6.0,210,21,29,3362,107,189
391,Toyota,Camry Solara SLE V6 2dr,Sedan,Asia,Front,"$26,510","$23,908",3.3,6.0,225,20,29,3439,107,193
392,Toyota,Avalon XLS 4dr,Sedan,Asia,Front,"$30,920","$27,271",3.0,6.0,210,21,29,3439,107,192
393,Toyota,Sienna CE,Sedan,Asia,Front,"$23,495","$21,198",3.3,6.0,230,19,27,4120,119,200
394,Toyota,Sienna XLE Limited,Sedan,Asia,Front,"$28,800","$25,690",3.3,6.0,230,19,27,4165,119,200
395,Toyota,Celica GT-S 2dr,Sports,Asia,Front,"$22,570","$20,363",1.8,4.0,180,24,33,2500,102,171
396,Toyota,MR2 Spyder convertible 2dr,Sports,Asia,Rear,"$25,130","$22,787",1.8,4.0,138,26,32,2195,97,153
397,Toyota,Tacoma,Truck,Asia,Rear,"$12,800","$11,879",2.4,4.0,142,22,27,2750,103,191
398,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190,16,18,3925,128,218
399,Toyota,Tundra Access Cab V6 SR5,Truck,Asia,All,"$25,935","$23,520",3.4,6.0,190,14,17,4435,128,218
400,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130,29,36,2679,102,171
401,Volkswagen,Touareg V6,SUV,Europe,All,"$35,515","$32,243",3.2,6.0,220,15,20,5086,112,187
402,Volkswagen,Golf GLS 4dr,Sedan,Europe,Front,"$18,715","$17,478",2.0,4.0,115,24,31,2897,99,165
403,Volkswagen,GTI 1.8T 2dr hatch,Sedan,Europe,Front,"$19,825","$18,109",1.8,4.0,180,24,31,2934,99,168
404,Volkswagen,Jetta GLS TDI 4dr,Sedan,Europe,Front,"$21,055","$19,638",1.9,4.0,100,38,46,3003,99,172
405,Volkswagen,New Beetle GLS 1.8T 2dr,Sedan,Europe,Front,"$21,055","$19,638",1.8,4.0,150,24,31,2820,99,161
406,Volkswagen,Jetta GLI VR6 4dr,Sedan,Europe,Front,"$23,785","$21,686",2.8,6.0,200,21,30,3179,99,172
407,Volkswagen,New Beetle GLS convertible 2dr,Sedan,Europe,Front,"$23,215","$21,689",2.0,4.0,115,24,30,3082,99,161
408,Volkswagen,Passat GLS 4dr,Sedan,Europe,Front,"$23,955","$21,898",1.8,4.0,170,22,31,3241,106,185
409,Volkswagen,Passat GLX V6 4MOTION 4dr,Sedan,Europe,Front,"$33,180","$30,583",2.8,6.0,190,19,26,3721,106,185
410,Volkswagen,Passat W8 4MOTION 4dr,Sedan,Europe,Front,"$39,235","$36,052",4.0,8.0,270,18,25,3953,106,185
411,Volkswagen,Phaeton 4dr,Sedan,Europe,Front,"$65,000","$59,912",4.2,8.0,335,16,22,5194,118,204
412,Volkswagen,Phaeton W12 4dr,Sedan,Europe,Front,"$75,000","$69,130",6.0,12.0,420,12,19,5399,118,204
413,Volkswagen,Jetta GL,Wagon,Europe,Front,"$19,005","$17,427",2.0,4.0,115,24,30,3034,99,174
414,Volkswagen,Passat GLS 1.8T,Wagon,Europe,Front,"$24,955","$22,801",1.8,4.0,170,22,31,3338,106,184
415,Volkswagen,Passat W8,Wagon,Europe,Front,"$40,235","$36,956",4.0,8.0,270,18,25,4067,106,184
416,Volvo,XC90 T6,SUV,Europe,All,"$41,250","$38,851",2.9,6.0,268,15,20,4638,113,189
417,Volvo,S40 4dr,Sedan,Europe,Front,"$25,135","$23,701",1.9,4.0,170,22,29,2767,101,178
418,Volvo,S60 2.5 4dr,Sedan,Europe,All,"$31,745","$29,916",2.5,5.0,208,20,27,3903,107,180
419,Volvo,S60 T5 4dr,Sedan,Europe,Front,"$34,845","$32,902",2.3,5.0,247,20,28,3766,107,180
420,Volvo,S60 R 4dr,Sedan,Europe,All,"$37,560","$35,382",2.5,5.0,300,18,25,3571,107,181
421,Volvo,S80 2.9 4dr,Sedan,Europe,Front,"$37,730","$35,542",2.9,6.0,208,20,28,3576,110,190
422,Volvo,S80 2.5T 4dr,Sedan,Europe,All,"$37,885","$35,688",2.5,5.0,194,20,27,3691,110,190
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

# 4) Instruction (Removing unwanted records)
	Remove all the records(rows) where Weight is above 4000

In [30]:
car.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172

In [34]:
#use ~  this sign for remove..
car[~(car['Weight'] > 4000)]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180,20,28,3131,95,159
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184,20,29,3219,107,176
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184,20,29,3197,107,177
30,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184,19,27,3560,107,177
31,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184,19,27,3461,107,176
32,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225,20,30,3285,107,176
33,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225,20,30,3285,107,176
34,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225,20,29,3483,107,176
35,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.0,184,19,28,3428,114,191
36,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225,19,28,3616,107,177
37,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.0,225,20,30,3472,114,191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,Toyota,Camry XLE V6 4dr,Sedan,Asia,Front,"$25,920","$23,125",3.0,6.0,210,21,29,3362,107,189
391,Toyota,Camry Solara SLE V6 2dr,Sedan,Asia,Front,"$26,510","$23,908",3.3,6.0,225,20,29,3439,107,193
392,Toyota,Avalon XLS 4dr,Sedan,Asia,Front,"$30,920","$27,271",3.0,6.0,210,21,29,3439,107,192
395,Toyota,Celica GT-S 2dr,Sports,Asia,Front,"$22,570","$20,363",1.8,4.0,180,24,33,2500,102,171
396,Toyota,MR2 Spyder convertible 2dr,Sports,Asia,Rear,"$25,130","$22,787",1.8,4.0,138,26,32,2195,97,153
397,Toyota,Tacoma,Truck,Asia,Rear,"$12,800","$11,879",2.4,4.0,142,22,27,2750,103,191
398,Toyota,Tundra Regular Cab V6,Truck,Asia,Rear,"$16,495","$14,978",3.4,6.0,190,16,18,3925,128,218
400,Toyota,Matrix XR,Wagon,Asia,Front,"$16,695","$15,156",1.8,4.0,130,29,36,2679,102,171
402,Volkswagen,Golf GLS 4dr,Sedan,Europe,Front,"$18,715","$17,478",2.0,4.0,115,24,31,2897,99,165
403,Volkswagen,GTI 1.8T 2dr hatch,Sedan,Europe,Front,"$19,825","$18,109",1.8,4.0,180,24,31,2934,99,168
404,Volkswagen,Jetta GLS TDI 4dr,Sedan,Europe,Front,"$21,055","$19,638",1.9,4.0,100,38,46,3003,99,172
405,Volkswagen,New Beetle GLS 1.8T 2dr,Sedan,Europe,Front,"$21,055","$19,638",1.8,4.0,150,24,31,2820,99,161
406,Volkswagen,Jetta GLI VR6 4dr,Sedan,Europe,Front,"$23,785","$21,686",2.8,6.0,200,21,30,3179,99,172
407,Volkswagen,New Beetle GLS convertible 2dr,Sedan,Europe,Front,"$23,215","$21,689",2.0,4.0,115,24,30,3082,99,161
408,Volkswagen,Passat GLS 4dr,Sedan,Europe,Front,"$23,955","$21,898",1.8,4.0,170,22,31,3241,106,185
409,Volkswagen,Passat GLX V6 4MOTION 4dr,Sedan,Europe,Front,"$33,180","$30,583",2.8,6.0,190,19,26,3721,106,185
410,Volkswagen,Passat W8 4MOTION 4dr,Sedan,Europe,Front,"$39,235","$36,052",4.0,8.0,270,18,25,3953,106,185
413,Volkswagen,Jetta GL,Wagon,Europe,Front,"$19,005","$17,427",2.0,4.0,115,24,30,3034,99,174
414,Volkswagen,Passat GLS 1.8T,Wagon,Europe,Front,"$24,955","$22,801",1.8,4.0,170,22,31,3338,106,184
417,Volvo,S40 4dr,Sedan,Europe,Front,"$25,135","$23,701",1.9,4.0,170,22,29,2767,101,178
418,Volvo,S60 2.5 4dr,Sedan,Europe,All,"$31,745","$29,916",2.5,5.0,208,20,27,3903,107,180
419,Volvo,S60 T5 4dr,Sedan,Europe,Front,"$34,845","$32,902",2.3,5.0,247,20,28,3766,107,180
420,Volvo,S60 R 4dr,Sedan,Europe,All,"$37,560","$35,382",2.5,5.0,300,18,25,3571,107,181
421,Volvo,S80 2.9 4dr,Sedan,Europe,Front,"$37,730","$35,542",2.9,6.0,208,20,28,3576,110,190
422,Volvo,S80 2.5T 4dr,Sedan,Europe,All,"$37,885","$35,688",2.5,5.0,194,20,27,3691,110,190
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

# 5) Instruction (Applying function on a column)
	increase all the values of "MPG_City" column by 3

In [35]:
car.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172

In [36]:
car['MPG_City'] = car['MPG_City'].apply(lambda x:x+3)

In [37]:
car.head(5)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,20,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,27,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,25,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,23,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,21,24,3880,115,197